name: kobo_kobo
description: "A new Flutter project."
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.7.0
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  # tooling and security
  dartz: ^0.10.1
  encrypt: ^5.0.1
  equatable: ^2.0.5
  intl: 0.20.2
  jwt_decoder: ^2.0.1
  pinput: ^5.0.1

  # # state and data mgt
  path_provider: ^2.1.5
  shared_preferences: ^2.5.2
  provider: ^6.1.2
  flutter_secure_storage: ^9.2.4

  # # network tooling
  connectivity_plus: ^6.1.3
  dio: ^5.8.0+1
  http: any

  # # DI
  get_it: ^8.0.3

  # UI
  auto_size_text: ^3.0.0
  cached_network_image: ^3.3.1
  carousel_slider: ^5.0.0
  country_pickers: ^2.0.0
  country_currency_pickers: ^3.0.0
  dropdown_button2: ^2.3.9
  flutter_localizations:
    sdk: flutter
  flutter_staggered_animations: ^1.1.1
  flutter_svg: ^2.0.9
  go_router: ^13.0.0
  overlay_support: ^2.1.0
  phosphor_flutter: ^2.0.1
  url_launcher: ^6.1.4
  webview_flutter: ^4.0.5
  webview_flutter_android: ^3.3.1
  webview_flutter_wkwebview: ^3.1.1
  flutter_slidable: ^3.0.1
  flutter_contacts: ^1.1.7+1
  intl_phone_field: ^3.2.0
  file: ^7.0.0
  google_fonts: 6.1.0
  flutter_datetime_picker: ^1.5.1
  flutter_phosphor_icons: ^0.0.1+6
  shimmer: ^3.0.0
  skeletonizer: 2.1.0
  smooth_page_indicator: ^1.1.0
  flutter_screenutil: ^5.9.3
  dotted_border: ^2.0.0+3

  # App Tooling Dependencies
  camera: ^0.11.1
  file_picker: ^9.0.0
  flutter_dotenv: ^5.0.0
  share_plus: ^10.1.4
  image_picker: ^1.0.5
  permission_handler: ^11.3.1
  local_auth: ^2.3.0
  flutter_vector_icons: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

  # flutter_launcher_icons: ^0.14.2
  # flutter_launcher_icons:
  #   android: "launcher_icon"
  #   ios: true
  #   image_path: "assets/png/logo/logo.png"
  #   min_sdk_android: 21 # android min sdk min:16, default 21

flutter:
  uses-material-design: true
  fonts:
    - family: KoboGra
      fonts:
        - asset: assets/fonts/Gracheva.otf
  assets:
    - assets/svg/
    - assets/svg/flag/
    - assets/svg/nav/
    - assets/svg/dashboard/
    # - assets/gif/
    - assets/png/
    - assets/png/logo/
    - assets/png/bg/
    - assets/png/onboarding/
    - assets/png/dash/
    - assets/png/savings/
    - assets/png/loans/
    - assets/png/emp_detail/
    - assets/png/notify/
    - assets/png/more/
    - .env
