export 'screen/loan_home_page.dart';
export 'screen/loan_page.dart';
export 'screen/salary_loan/loan_application.dart';
export 'screen/salary_loan/salary_loan_homePage.dart';
export 'screen/salary_loan/loan_overlay.dart';
export 'screen/salary_loan/reg_con_app.dart';
export 'screen/salary_loan/reg_sal_app.dart';
export 'screen/easi_loan/easy_loan_view_all.dart';
export 'screen/easi_loan/easy_loan_add_new.dart';
export 'screen/easi_loan/easy_loan_details_screen.dart';
export 'screen/easi_loan/easy_loan_pin.dart';
export 'screen/easi_loan/easy_loan_view_all_pin.dart';
export 'screen/salary_loan/confirmation_screen.dart';
export 'screen/salary_loan/loan_app_form.dart';
export 'screen/salary_loan/pinLoan.dart';
export 'screen/salary_loan/sal_loan_pin.dart';
export 'screen/salary_loan/salary_loan_details_screen.dart';
export 'screen/easi_loan/loan_success_modal.dart';
// export 'screen/salary_loan/reg_sal_app.dart';
// export 'screen/salary_loan/reg_sal_app.dart';
// export 'screen/salary_loan/reg_sal_app.dart';
